apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: che-tls
spec:
  secretName: che-tls
  dnsNames:
    - '*.eclipse.gosimplyee.info'
  issuerRef:
    name: che-certificate-issuer
    kind: ClusterIssuer
