apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: che-tls
 namespace: che
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
 dnsNames:
   - '*.eclipse.gosimplyee.info'
 acme:
   config:
     - dns01:
         provider: route53
       domains:
         - '*.eclipse.gosimplyee.info'
