apiVersion:  cert-manager.io/v1
kind: Certificate
metadata:
 name: che-tls
 namespace: che
spec:
 secretName: aws-cert-manager-access-key
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
 dnsNames:
   - '*.eclipse.mydomain.com'
