---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: che-tls
  namespace: cert-manager
spec:
  secretName: che-tls
  duration: 2160h
  renewBefore: 360h
  commonName: eclipse.gosimplyee.info
  dnsNames:
    - eclipse.gosimplyee.info
  issuerRef:
    name: che-certificate-issuer
    kind: ClusterIssuer
  acme:
    config:
      - dns01:
          provider: route53
        domains:
          - "*.eclipse.gosimplyee.info"
