apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: che-tls
 namespace: che
spec:
  secretName: che-tls
  dnsNames:
    - '*.eclipse.gosimplyee.info'
  issuerRef:
    name: che-certificate-issuer
    kind: ClusterIssuer
  acme:
    config:
      - dns01:
          provider: route53
        domains:
         - '*.eclipse.gosimplyee.info'
