apiVersion:  cert-manager.io/v1
kind: Certificate
metadata:
 name: che-tls
 namespace: cert-manager
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
 dnsNames:
   - '*.eclipse.gosimplyee.info'
