apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: che-certificate-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sandeepsinghitech@outlook.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: eu-west-1
            accessKeyID: AKIAW6ZEG6GJTID33KP5
            secretAccessKeySecretRef:
              name: aws-route53-credentials
              key: CLIENT_SECRET
